name: ollama-qwen
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - fastapi>=0.115.0
      - uvicorn>=0.32.0
      - ollama>=0.4.0
      - chromadb>=0.5.0


# # 创建环境（如果已存在会提示）
# conda env create -f environment.yml
# # 激活
# conda activate ollama-qwen
# # 如果后续更新了 yml，同步更新环境
# conda env update -f environment.yml --prune